### ISSUE TITLE
分片上传成功后需要访问哪个api查询合并结果？

### ISSUE THREAD

**Issue by ykxVK8yL5L** [tmplink/tmpui_tmplink#184]
您好，目前通过访问/app/upload_splice已经实现成功上传分片。状态码为5，然后该如何操作呢？再次访问prepare的话就成了未上传的状态。我用的是form的方式上传。是header中需要设置特殊字段？ 我通过调试官方接口发现header中有multipart/form-data; boundary=信息。请问boundary是否为必需设置？
期待您的回复 
谢谢！

**Comment by tmplink** [comment]
请暂时别研究这个接口，因为新的上传接口马上就要上线了，改了一些参数。
